/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import sc.modelica.xtext.modelicaMo.AlgorithmSection;
import sc.modelica.xtext.modelicaMo.Annotation;
import sc.modelica.xtext.modelicaMo.Composition;
import sc.modelica.xtext.modelicaMo.ElementList;
import sc.modelica.xtext.modelicaMo.EquationSection;
import sc.modelica.xtext.modelicaMo.ModelicaMoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Composition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getElementList <em>Element List</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getElementListPublic <em>Element List Public</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getElementListProtected <em>Element List Protected</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getEquationSections <em>Equation Sections</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getAlgorithmSections <em>Algorithm Sections</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getLanguageSpecification <em>Language Specification</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.CompositionImpl#getAnnotation <em>Annotation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompositionImpl extends MinimalEObjectImpl.Container implements Composition
{
  /**
   * The cached value of the '{@link #getElementList() <em>Element List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElementList()
   * @generated
   * @ordered
   */
  protected ElementList elementList;

  /**
   * The cached value of the '{@link #getElementListPublic() <em>Element List Public</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElementListPublic()
   * @generated
   * @ordered
   */
  protected EList<ElementList> elementListPublic;

  /**
   * The cached value of the '{@link #getElementListProtected() <em>Element List Protected</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElementListProtected()
   * @generated
   * @ordered
   */
  protected EList<ElementList> elementListProtected;

  /**
   * The cached value of the '{@link #getEquationSections() <em>Equation Sections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEquationSections()
   * @generated
   * @ordered
   */
  protected EList<EquationSection> equationSections;

  /**
   * The cached value of the '{@link #getAlgorithmSections() <em>Algorithm Sections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgorithmSections()
   * @generated
   * @ordered
   */
  protected EList<AlgorithmSection> algorithmSections;

  /**
   * The default value of the '{@link #getLanguageSpecification() <em>Language Specification</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLanguageSpecification()
   * @generated
   * @ordered
   */
  protected static final String LANGUAGE_SPECIFICATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLanguageSpecification() <em>Language Specification</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLanguageSpecification()
   * @generated
   * @ordered
   */
  protected String languageSpecification = LANGUAGE_SPECIFICATION_EDEFAULT;

  /**
   * The cached value of the '{@link #getAnnotation() <em>Annotation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotation()
   * @generated
   * @ordered
   */
  protected Annotation annotation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompositionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaMoPackage.Literals.COMPOSITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ElementList getElementList()
  {
    return elementList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElementList(ElementList newElementList, NotificationChain msgs)
  {
    ElementList oldElementList = elementList;
    elementList = newElementList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.COMPOSITION__ELEMENT_LIST, oldElementList, newElementList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElementList(ElementList newElementList)
  {
    if (newElementList != elementList)
    {
      NotificationChain msgs = null;
      if (elementList != null)
        msgs = ((InternalEObject)elementList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.COMPOSITION__ELEMENT_LIST, null, msgs);
      if (newElementList != null)
        msgs = ((InternalEObject)newElementList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.COMPOSITION__ELEMENT_LIST, null, msgs);
      msgs = basicSetElementList(newElementList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.COMPOSITION__ELEMENT_LIST, newElementList, newElementList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ElementList> getElementListPublic()
  {
    if (elementListPublic == null)
    {
      elementListPublic = new EObjectContainmentEList<ElementList>(ElementList.class, this, ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC);
    }
    return elementListPublic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ElementList> getElementListProtected()
  {
    if (elementListProtected == null)
    {
      elementListProtected = new EObjectContainmentEList<ElementList>(ElementList.class, this, ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED);
    }
    return elementListProtected;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EquationSection> getEquationSections()
  {
    if (equationSections == null)
    {
      equationSections = new EObjectContainmentEList<EquationSection>(EquationSection.class, this, ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS);
    }
    return equationSections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AlgorithmSection> getAlgorithmSections()
  {
    if (algorithmSections == null)
    {
      algorithmSections = new EObjectContainmentEList<AlgorithmSection>(AlgorithmSection.class, this, ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS);
    }
    return algorithmSections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLanguageSpecification()
  {
    return languageSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLanguageSpecification(String newLanguageSpecification)
  {
    String oldLanguageSpecification = languageSpecification;
    languageSpecification = newLanguageSpecification;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.COMPOSITION__LANGUAGE_SPECIFICATION, oldLanguageSpecification, languageSpecification));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Annotation getAnnotation()
  {
    return annotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAnnotation(Annotation newAnnotation, NotificationChain msgs)
  {
    Annotation oldAnnotation = annotation;
    annotation = newAnnotation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.COMPOSITION__ANNOTATION, oldAnnotation, newAnnotation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAnnotation(Annotation newAnnotation)
  {
    if (newAnnotation != annotation)
    {
      NotificationChain msgs = null;
      if (annotation != null)
        msgs = ((InternalEObject)annotation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.COMPOSITION__ANNOTATION, null, msgs);
      if (newAnnotation != null)
        msgs = ((InternalEObject)newAnnotation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.COMPOSITION__ANNOTATION, null, msgs);
      msgs = basicSetAnnotation(newAnnotation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.COMPOSITION__ANNOTATION, newAnnotation, newAnnotation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST:
        return basicSetElementList(null, msgs);
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC:
        return ((InternalEList<?>)getElementListPublic()).basicRemove(otherEnd, msgs);
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED:
        return ((InternalEList<?>)getElementListProtected()).basicRemove(otherEnd, msgs);
      case ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS:
        return ((InternalEList<?>)getEquationSections()).basicRemove(otherEnd, msgs);
      case ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS:
        return ((InternalEList<?>)getAlgorithmSections()).basicRemove(otherEnd, msgs);
      case ModelicaMoPackage.COMPOSITION__ANNOTATION:
        return basicSetAnnotation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST:
        return getElementList();
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC:
        return getElementListPublic();
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED:
        return getElementListProtected();
      case ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS:
        return getEquationSections();
      case ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS:
        return getAlgorithmSections();
      case ModelicaMoPackage.COMPOSITION__LANGUAGE_SPECIFICATION:
        return getLanguageSpecification();
      case ModelicaMoPackage.COMPOSITION__ANNOTATION:
        return getAnnotation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST:
        setElementList((ElementList)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC:
        getElementListPublic().clear();
        getElementListPublic().addAll((Collection<? extends ElementList>)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED:
        getElementListProtected().clear();
        getElementListProtected().addAll((Collection<? extends ElementList>)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS:
        getEquationSections().clear();
        getEquationSections().addAll((Collection<? extends EquationSection>)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS:
        getAlgorithmSections().clear();
        getAlgorithmSections().addAll((Collection<? extends AlgorithmSection>)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__LANGUAGE_SPECIFICATION:
        setLanguageSpecification((String)newValue);
        return;
      case ModelicaMoPackage.COMPOSITION__ANNOTATION:
        setAnnotation((Annotation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST:
        setElementList((ElementList)null);
        return;
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC:
        getElementListPublic().clear();
        return;
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED:
        getElementListProtected().clear();
        return;
      case ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS:
        getEquationSections().clear();
        return;
      case ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS:
        getAlgorithmSections().clear();
        return;
      case ModelicaMoPackage.COMPOSITION__LANGUAGE_SPECIFICATION:
        setLanguageSpecification(LANGUAGE_SPECIFICATION_EDEFAULT);
        return;
      case ModelicaMoPackage.COMPOSITION__ANNOTATION:
        setAnnotation((Annotation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST:
        return elementList != null;
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PUBLIC:
        return elementListPublic != null && !elementListPublic.isEmpty();
      case ModelicaMoPackage.COMPOSITION__ELEMENT_LIST_PROTECTED:
        return elementListProtected != null && !elementListProtected.isEmpty();
      case ModelicaMoPackage.COMPOSITION__EQUATION_SECTIONS:
        return equationSections != null && !equationSections.isEmpty();
      case ModelicaMoPackage.COMPOSITION__ALGORITHM_SECTIONS:
        return algorithmSections != null && !algorithmSections.isEmpty();
      case ModelicaMoPackage.COMPOSITION__LANGUAGE_SPECIFICATION:
        return LANGUAGE_SPECIFICATION_EDEFAULT == null ? languageSpecification != null : !LANGUAGE_SPECIFICATION_EDEFAULT.equals(languageSpecification);
      case ModelicaMoPackage.COMPOSITION__ANNOTATION:
        return annotation != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (LanguageSpecification: ");
    result.append(languageSpecification);
    result.append(')');
    return result.toString();
  }

} //CompositionImpl
