/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import sc.modelica.xtext.modelicaMo.ClassDefinition;
import sc.modelica.xtext.modelicaMo.Comment;
import sc.modelica.xtext.modelicaMo.ComponentClause;
import sc.modelica.xtext.modelicaMo.ConstrainingClause;
import sc.modelica.xtext.modelicaMo.Element;
import sc.modelica.xtext.modelicaMo.ExtendClause;
import sc.modelica.xtext.modelicaMo.ImportClause;
import sc.modelica.xtext.modelicaMo.ModelicaMoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getImportClause <em>Import Clause</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getExtendClause <em>Extend Clause</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#isRedeclare <em>Redeclare</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#isFinal <em>Final</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#isInner <em>Inner</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#isOuter <em>Outer</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getClass_ <em>Class</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getComp <em>Comp</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getCc <em>Cc</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.impl.ElementImpl#getComment <em>Comment</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ElementImpl extends MinimalEObjectImpl.Container implements Element
{
  /**
   * The cached value of the '{@link #getImportClause() <em>Import Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportClause()
   * @generated
   * @ordered
   */
  protected ImportClause importClause;

  /**
   * The cached value of the '{@link #getExtendClause() <em>Extend Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtendClause()
   * @generated
   * @ordered
   */
  protected ExtendClause extendClause;

  /**
   * The default value of the '{@link #isRedeclare() <em>Redeclare</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRedeclare()
   * @generated
   * @ordered
   */
  protected static final boolean REDECLARE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRedeclare() <em>Redeclare</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRedeclare()
   * @generated
   * @ordered
   */
  protected boolean redeclare = REDECLARE_EDEFAULT;

  /**
   * The default value of the '{@link #isFinal() <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinal()
   * @generated
   * @ordered
   */
  protected static final boolean FINAL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFinal() <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinal()
   * @generated
   * @ordered
   */
  protected boolean final_ = FINAL_EDEFAULT;

  /**
   * The default value of the '{@link #isInner() <em>Inner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isInner()
   * @generated
   * @ordered
   */
  protected static final boolean INNER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isInner() <em>Inner</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isInner()
   * @generated
   * @ordered
   */
  protected boolean inner = INNER_EDEFAULT;

  /**
   * The default value of the '{@link #isOuter() <em>Outer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOuter()
   * @generated
   * @ordered
   */
  protected static final boolean OUTER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOuter() <em>Outer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOuter()
   * @generated
   * @ordered
   */
  protected boolean outer = OUTER_EDEFAULT;

  /**
   * The cached value of the '{@link #getClass_() <em>Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClass_()
   * @generated
   * @ordered
   */
  protected ClassDefinition class_;

  /**
   * The cached value of the '{@link #getComp() <em>Comp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComp()
   * @generated
   * @ordered
   */
  protected ComponentClause comp;

  /**
   * The cached value of the '{@link #getCc() <em>Cc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCc()
   * @generated
   * @ordered
   */
  protected ConstrainingClause cc;

  /**
   * The cached value of the '{@link #getComment() <em>Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComment()
   * @generated
   * @ordered
   */
  protected Comment comment;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaMoPackage.Literals.ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImportClause getImportClause()
  {
    return importClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImportClause(ImportClause newImportClause, NotificationChain msgs)
  {
    ImportClause oldImportClause = importClause;
    importClause = newImportClause;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE, oldImportClause, newImportClause);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImportClause(ImportClause newImportClause)
  {
    if (newImportClause != importClause)
    {
      NotificationChain msgs = null;
      if (importClause != null)
        msgs = ((InternalEObject)importClause).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE, null, msgs);
      if (newImportClause != null)
        msgs = ((InternalEObject)newImportClause).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE, null, msgs);
      msgs = basicSetImportClause(newImportClause, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE, newImportClause, newImportClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExtendClause getExtendClause()
  {
    return extendClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExtendClause(ExtendClause newExtendClause, NotificationChain msgs)
  {
    ExtendClause oldExtendClause = extendClause;
    extendClause = newExtendClause;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE, oldExtendClause, newExtendClause);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExtendClause(ExtendClause newExtendClause)
  {
    if (newExtendClause != extendClause)
    {
      NotificationChain msgs = null;
      if (extendClause != null)
        msgs = ((InternalEObject)extendClause).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE, null, msgs);
      if (newExtendClause != null)
        msgs = ((InternalEObject)newExtendClause).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE, null, msgs);
      msgs = basicSetExtendClause(newExtendClause, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE, newExtendClause, newExtendClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isRedeclare()
  {
    return redeclare;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRedeclare(boolean newRedeclare)
  {
    boolean oldRedeclare = redeclare;
    redeclare = newRedeclare;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__REDECLARE, oldRedeclare, redeclare));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isFinal()
  {
    return final_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFinal(boolean newFinal)
  {
    boolean oldFinal = final_;
    final_ = newFinal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__FINAL, oldFinal, final_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isInner()
  {
    return inner;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInner(boolean newInner)
  {
    boolean oldInner = inner;
    inner = newInner;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__INNER, oldInner, inner));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isOuter()
  {
    return outer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOuter(boolean newOuter)
  {
    boolean oldOuter = outer;
    outer = newOuter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__OUTER, oldOuter, outer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassDefinition getClass_()
  {
    return class_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetClass(ClassDefinition newClass, NotificationChain msgs)
  {
    ClassDefinition oldClass = class_;
    class_ = newClass;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__CLASS, oldClass, newClass);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setClass(ClassDefinition newClass)
  {
    if (newClass != class_)
    {
      NotificationChain msgs = null;
      if (class_ != null)
        msgs = ((InternalEObject)class_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__CLASS, null, msgs);
      if (newClass != null)
        msgs = ((InternalEObject)newClass).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__CLASS, null, msgs);
      msgs = basicSetClass(newClass, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__CLASS, newClass, newClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentClause getComp()
  {
    return comp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComp(ComponentClause newComp, NotificationChain msgs)
  {
    ComponentClause oldComp = comp;
    comp = newComp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__COMP, oldComp, newComp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComp(ComponentClause newComp)
  {
    if (newComp != comp)
    {
      NotificationChain msgs = null;
      if (comp != null)
        msgs = ((InternalEObject)comp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__COMP, null, msgs);
      if (newComp != null)
        msgs = ((InternalEObject)newComp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__COMP, null, msgs);
      msgs = basicSetComp(newComp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__COMP, newComp, newComp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstrainingClause getCc()
  {
    return cc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCc(ConstrainingClause newCc, NotificationChain msgs)
  {
    ConstrainingClause oldCc = cc;
    cc = newCc;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__CC, oldCc, newCc);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCc(ConstrainingClause newCc)
  {
    if (newCc != cc)
    {
      NotificationChain msgs = null;
      if (cc != null)
        msgs = ((InternalEObject)cc).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__CC, null, msgs);
      if (newCc != null)
        msgs = ((InternalEObject)newCc).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__CC, null, msgs);
      msgs = basicSetCc(newCc, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__CC, newCc, newCc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Comment getComment()
  {
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComment(Comment newComment, NotificationChain msgs)
  {
    Comment oldComment = comment;
    comment = newComment;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__COMMENT, oldComment, newComment);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComment(Comment newComment)
  {
    if (newComment != comment)
    {
      NotificationChain msgs = null;
      if (comment != null)
        msgs = ((InternalEObject)comment).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__COMMENT, null, msgs);
      if (newComment != null)
        msgs = ((InternalEObject)newComment).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ModelicaMoPackage.ELEMENT__COMMENT, null, msgs);
      msgs = basicSetComment(newComment, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ModelicaMoPackage.ELEMENT__COMMENT, newComment, newComment));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE:
        return basicSetImportClause(null, msgs);
      case ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE:
        return basicSetExtendClause(null, msgs);
      case ModelicaMoPackage.ELEMENT__CLASS:
        return basicSetClass(null, msgs);
      case ModelicaMoPackage.ELEMENT__COMP:
        return basicSetComp(null, msgs);
      case ModelicaMoPackage.ELEMENT__CC:
        return basicSetCc(null, msgs);
      case ModelicaMoPackage.ELEMENT__COMMENT:
        return basicSetComment(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE:
        return getImportClause();
      case ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE:
        return getExtendClause();
      case ModelicaMoPackage.ELEMENT__REDECLARE:
        return isRedeclare();
      case ModelicaMoPackage.ELEMENT__FINAL:
        return isFinal();
      case ModelicaMoPackage.ELEMENT__INNER:
        return isInner();
      case ModelicaMoPackage.ELEMENT__OUTER:
        return isOuter();
      case ModelicaMoPackage.ELEMENT__CLASS:
        return getClass_();
      case ModelicaMoPackage.ELEMENT__COMP:
        return getComp();
      case ModelicaMoPackage.ELEMENT__CC:
        return getCc();
      case ModelicaMoPackage.ELEMENT__COMMENT:
        return getComment();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE:
        setImportClause((ImportClause)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE:
        setExtendClause((ExtendClause)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__REDECLARE:
        setRedeclare((Boolean)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__FINAL:
        setFinal((Boolean)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__INNER:
        setInner((Boolean)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__OUTER:
        setOuter((Boolean)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__CLASS:
        setClass((ClassDefinition)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__COMP:
        setComp((ComponentClause)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__CC:
        setCc((ConstrainingClause)newValue);
        return;
      case ModelicaMoPackage.ELEMENT__COMMENT:
        setComment((Comment)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE:
        setImportClause((ImportClause)null);
        return;
      case ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE:
        setExtendClause((ExtendClause)null);
        return;
      case ModelicaMoPackage.ELEMENT__REDECLARE:
        setRedeclare(REDECLARE_EDEFAULT);
        return;
      case ModelicaMoPackage.ELEMENT__FINAL:
        setFinal(FINAL_EDEFAULT);
        return;
      case ModelicaMoPackage.ELEMENT__INNER:
        setInner(INNER_EDEFAULT);
        return;
      case ModelicaMoPackage.ELEMENT__OUTER:
        setOuter(OUTER_EDEFAULT);
        return;
      case ModelicaMoPackage.ELEMENT__CLASS:
        setClass((ClassDefinition)null);
        return;
      case ModelicaMoPackage.ELEMENT__COMP:
        setComp((ComponentClause)null);
        return;
      case ModelicaMoPackage.ELEMENT__CC:
        setCc((ConstrainingClause)null);
        return;
      case ModelicaMoPackage.ELEMENT__COMMENT:
        setComment((Comment)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ModelicaMoPackage.ELEMENT__IMPORT_CLAUSE:
        return importClause != null;
      case ModelicaMoPackage.ELEMENT__EXTEND_CLAUSE:
        return extendClause != null;
      case ModelicaMoPackage.ELEMENT__REDECLARE:
        return redeclare != REDECLARE_EDEFAULT;
      case ModelicaMoPackage.ELEMENT__FINAL:
        return final_ != FINAL_EDEFAULT;
      case ModelicaMoPackage.ELEMENT__INNER:
        return inner != INNER_EDEFAULT;
      case ModelicaMoPackage.ELEMENT__OUTER:
        return outer != OUTER_EDEFAULT;
      case ModelicaMoPackage.ELEMENT__CLASS:
        return class_ != null;
      case ModelicaMoPackage.ELEMENT__COMP:
        return comp != null;
      case ModelicaMoPackage.ELEMENT__CC:
        return cc != null;
      case ModelicaMoPackage.ELEMENT__COMMENT:
        return comment != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (redeclare: ");
    result.append(redeclare);
    result.append(", final: ");
    result.append(final_);
    result.append(", inner: ");
    result.append(inner);
    result.append(", outer: ");
    result.append(outer);
    result.append(')');
    return result.toString();
  }

} //ElementImpl
