/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo.impl;

import org.eclipse.emf.ecore.EClass;

import sc.modelica.xtext.modelicaMo.LayerDiagram;
import sc.modelica.xtext.modelicaMo.ModelicaMoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Layer Diagram</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LayerDiagramImpl extends AnnotationLayerImpl implements LayerDiagram
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LayerDiagramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaMoPackage.Literals.LAYER_DIAGRAM;
  }

} //LayerDiagramImpl
