/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo.impl;

import org.eclipse.emf.ecore.EClass;

import sc.modelica.xtext.modelicaMo.ModelicaMoPackage;
import sc.modelica.xtext.modelicaMo.OutputExpressionList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Output Expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OutputExpressionListImpl extends ExpressionImpl implements OutputExpressionList
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutputExpressionListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelicaMoPackage.Literals.OUTPUT_EXPRESSION_LIST;
  }

} //OutputExpressionListImpl
