/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sc.modelica.xtext.parser.antlr.internal.InternalModelicaMoParser;
import sc.modelica.xtext.services.ModelicaMoGrammarAccess;

public class ModelicaMoParser extends AbstractAntlrParser {

	@Inject
	private ModelicaMoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_S_ESCAPE", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModelicaMoParser createParser(XtextTokenStream stream) {
		return new InternalModelicaMoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ModelicaMoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModelicaMoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
