/*
 * generated by Xtext 2.9.1
 */
package sc.modelica.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelicaMoStandaloneSetup extends ModelicaMoStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelicaMoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
