/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getClassSpecifier()
 * @model
 * @generated
 */
public interface ClassSpecifier extends EObject
{
} // ClassSpecifier
