/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getDeclaration <em>Declaration</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getConditionAttribute <em>Condition Attribute</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getComment <em>Comment</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getAnnotation <em>Annotation</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentDeclaration()
 * @model
 * @generated
 */
public interface ComponentDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(Declaration)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentDeclaration_Declaration()
   * @model containment="true"
   * @generated
   */
  Declaration getDeclaration();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(Declaration value);

  /**
   * Returns the value of the '<em><b>Condition Attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition Attribute</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Attribute</em>' containment reference.
   * @see #setConditionAttribute(ConditionAttribute)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentDeclaration_ConditionAttribute()
   * @model containment="true"
   * @generated
   */
  ConditionAttribute getConditionAttribute();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getConditionAttribute <em>Condition Attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Attribute</em>' containment reference.
   * @see #getConditionAttribute()
   * @generated
   */
  void setConditionAttribute(ConditionAttribute value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' containment reference.
   * @see #setComment(StringComment)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentDeclaration_Comment()
   * @model containment="true"
   * @generated
   */
  StringComment getComment();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getComment <em>Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' containment reference.
   * @see #getComment()
   * @generated
   */
  void setComment(StringComment value);

  /**
   * Returns the value of the '<em><b>Annotation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotation</em>' containment reference.
   * @see #setAnnotation(Annotation)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentDeclaration_Annotation()
   * @model containment="true"
   * @generated
   */
  Annotation getAnnotation();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentDeclaration#getAnnotation <em>Annotation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annotation</em>' containment reference.
   * @see #getAnnotation()
   * @generated
   */
  void setAnnotation(Annotation value);

} // ComponentDeclaration
