/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Clause1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getTypePrefix <em>Type Prefix</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getTypeSpecifier <em>Type Specifier</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getComponentDeclaration <em>Component Declaration</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentClause1()
 * @model
 * @generated
 */
public interface ComponentClause1 extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Prefix</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Prefix</em>' containment reference.
   * @see #setTypePrefix(TypePrefix)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentClause1_TypePrefix()
   * @model containment="true"
   * @generated
   */
  TypePrefix getTypePrefix();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getTypePrefix <em>Type Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Prefix</em>' containment reference.
   * @see #getTypePrefix()
   * @generated
   */
  void setTypePrefix(TypePrefix value);

  /**
   * Returns the value of the '<em><b>Type Specifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Specifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Specifier</em>' containment reference.
   * @see #setTypeSpecifier(TypeSpecifier)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentClause1_TypeSpecifier()
   * @model containment="true"
   * @generated
   */
  TypeSpecifier getTypeSpecifier();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getTypeSpecifier <em>Type Specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Specifier</em>' containment reference.
   * @see #getTypeSpecifier()
   * @generated
   */
  void setTypeSpecifier(TypeSpecifier value);

  /**
   * Returns the value of the '<em><b>Component Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Declaration</em>' containment reference.
   * @see #setComponentDeclaration(ComponentDeclaration1)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getComponentClause1_ComponentDeclaration()
   * @model containment="true"
   * @generated
   */
  ComponentDeclaration1 getComponentDeclaration();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ComponentClause1#getComponentDeclaration <em>Component Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Declaration</em>' containment reference.
   * @see #getComponentDeclaration()
   * @generated
   */
  void setComponentDeclaration(ComponentDeclaration1 value);

} // ComponentClause1
