/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Redeclaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#isRedeclare <em>Redeclare</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getClassDefinition <em>Class Definition</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getComponentClause <em>Component Clause</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementRedeclaration()
 * @model
 * @generated
 */
public interface ElementRedeclaration extends Argument
{
  /**
   * Returns the value of the '<em><b>Redeclare</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Redeclare</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Redeclare</em>' attribute.
   * @see #setRedeclare(boolean)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementRedeclaration_Redeclare()
   * @model
   * @generated
   */
  boolean isRedeclare();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#isRedeclare <em>Redeclare</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Redeclare</em>' attribute.
   * @see #isRedeclare()
   * @generated
   */
  void setRedeclare(boolean value);

  /**
   * Returns the value of the '<em><b>Class Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Definition</em>' containment reference.
   * @see #setClassDefinition(ShortClassDefinition)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementRedeclaration_ClassDefinition()
   * @model containment="true"
   * @generated
   */
  ShortClassDefinition getClassDefinition();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getClassDefinition <em>Class Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Definition</em>' containment reference.
   * @see #getClassDefinition()
   * @generated
   */
  void setClassDefinition(ShortClassDefinition value);

  /**
   * Returns the value of the '<em><b>Component Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Clause</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Clause</em>' containment reference.
   * @see #setComponentClause(ComponentClause1)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementRedeclaration_ComponentClause()
   * @model containment="true"
   * @generated
   */
  ComponentClause1 getComponentClause();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getComponentClause <em>Component Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Clause</em>' containment reference.
   * @see #getComponentClause()
   * @generated
   */
  void setComponentClause(ComponentClause1 value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(ElementReplaceable)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementRedeclaration_Element()
   * @model containment="true"
   * @generated
   */
  ElementReplaceable getElement();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementRedeclaration#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(ElementReplaceable value);

} // ElementRedeclaration
