/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Replaceable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#isReplaceable <em>Replaceable</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#getElement <em>Element</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementReplaceable()
 * @model
 * @generated
 */
public interface ElementReplaceable extends EObject
{
  /**
   * Returns the value of the '<em><b>Replaceable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Replaceable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Replaceable</em>' attribute.
   * @see #setReplaceable(boolean)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementReplaceable_Replaceable()
   * @model
   * @generated
   */
  boolean isReplaceable();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#isReplaceable <em>Replaceable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Replaceable</em>' attribute.
   * @see #isReplaceable()
   * @generated
   */
  void setReplaceable(boolean value);

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(EObject)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementReplaceable_Element()
   * @model containment="true"
   * @generated
   */
  EObject getElement();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(EObject value);

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(ConstrainingClause)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementReplaceable_Constraint()
   * @model containment="true"
   * @generated
   */
  ConstrainingClause getConstraint();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementReplaceable#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(ConstrainingClause value);

} // ElementReplaceable
