/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Modification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementModification#getName <em>Name</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementModification#getModification <em>Modification</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.ElementModification#getStringComment <em>String Comment</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementModification()
 * @model
 * @generated
 */
public interface ElementModification extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Name)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementModification_Name()
   * @model containment="true"
   * @generated
   */
  Name getName();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementModification#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Name value);

  /**
   * Returns the value of the '<em><b>Modification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modification</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modification</em>' containment reference.
   * @see #setModification(Modification)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementModification_Modification()
   * @model containment="true"
   * @generated
   */
  Modification getModification();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementModification#getModification <em>Modification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modification</em>' containment reference.
   * @see #getModification()
   * @generated
   */
  void setModification(Modification value);

  /**
   * Returns the value of the '<em><b>String Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Comment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Comment</em>' containment reference.
   * @see #setStringComment(StringComment)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getElementModification_StringComment()
   * @model containment="true"
   * @generated
   */
  StringComment getStringComment();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.ElementModification#getStringComment <em>String Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Comment</em>' containment reference.
   * @see #getStringComment()
   * @generated
   */
  void setStringComment(StringComment value);

} // ElementModification
