/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ellipse</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getEllipse()
 * @model
 * @generated
 */
public interface Ellipse extends GraphicalPrimitive
{
} // Ellipse
