/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call Args</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.FunctionCallArgs#getFunctionArgs <em>Function Args</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getFunctionCallArgs()
 * @model
 * @generated
 */
public interface FunctionCallArgs extends EObject
{
  /**
   * Returns the value of the '<em><b>Function Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Args</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Args</em>' containment reference.
   * @see #setFunctionArgs(FunctionArguments)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getFunctionCallArgs_FunctionArgs()
   * @model containment="true"
   * @generated
   */
  FunctionArguments getFunctionArgs();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.FunctionCallArgs#getFunctionArgs <em>Function Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Args</em>' containment reference.
   * @see #getFunctionArgs()
   * @generated
   */
  void setFunctionArgs(FunctionArguments value);

} // FunctionCallArgs
