/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphical Primitive Args</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getPoints <em>Points</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getStr <em>Str</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getFileName <em>File Name</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getImageSource <em>Image Source</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getFillPattern <em>Fill Pattern</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs()
 * @model
 * @generated
 */
public interface GraphicalPrimitiveArgs extends EObject
{
  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link sc.modelica.xtext.modelicaMo.Point}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Points</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPoints();

  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

  /**
   * Returns the value of the '<em><b>File Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>File Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Name</em>' attribute.
   * @see #setFileName(String)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs_FileName()
   * @model
   * @generated
   */
  String getFileName();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getFileName <em>File Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File Name</em>' attribute.
   * @see #getFileName()
   * @generated
   */
  void setFileName(String value);

  /**
   * Returns the value of the '<em><b>Image Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Image Source</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image Source</em>' attribute.
   * @see #setImageSource(String)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs_ImageSource()
   * @model
   * @generated
   */
  String getImageSource();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getImageSource <em>Image Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image Source</em>' attribute.
   * @see #getImageSource()
   * @generated
   */
  void setImageSource(String value);

  /**
   * Returns the value of the '<em><b>Fill Pattern</b></em>' attribute.
   * The literals are from the enumeration {@link sc.modelica.xtext.modelicaMo.FillPattern}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fill Pattern</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fill Pattern</em>' attribute.
   * @see sc.modelica.xtext.modelicaMo.FillPattern
   * @see #setFillPattern(FillPattern)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getGraphicalPrimitiveArgs_FillPattern()
   * @model
   * @generated
   */
  FillPattern getFillPattern();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.GraphicalPrimitiveArgs#getFillPattern <em>Fill Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fill Pattern</em>' attribute.
   * @see sc.modelica.xtext.modelicaMo.FillPattern
   * @see #getFillPattern()
   * @generated
   */
  void setFillPattern(FillPattern value);

} // GraphicalPrimitiveArgs
