/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage
 * @generated
 */
public interface ModelicaMoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ModelicaMoFactory eINSTANCE = sc.modelica.xtext.modelicaMo.impl.ModelicaMoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Class Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Definition</em>'.
   * @generated
   */
  ClassDefinition createClassDefinition();

  /**
   * Returns a new object of class '<em>Class Prefixes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Prefixes</em>'.
   * @generated
   */
  ClassPrefixes createClassPrefixes();

  /**
   * Returns a new object of class '<em>Class Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Specifier</em>'.
   * @generated
   */
  ClassSpecifier createClassSpecifier();

  /**
   * Returns a new object of class '<em>Long Class Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Long Class Specifier</em>'.
   * @generated
   */
  LongClassSpecifier createLongClassSpecifier();

  /**
   * Returns a new object of class '<em>Short Class Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Short Class Specifier</em>'.
   * @generated
   */
  ShortClassSpecifier createShortClassSpecifier();

  /**
   * Returns a new object of class '<em>Der Class Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Der Class Specifier</em>'.
   * @generated
   */
  DerClassSpecifier createDerClassSpecifier();

  /**
   * Returns a new object of class '<em>Base Prefix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Base Prefix</em>'.
   * @generated
   */
  BasePrefix createBasePrefix();

  /**
   * Returns a new object of class '<em>Enum List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum List</em>'.
   * @generated
   */
  EnumList createEnumList();

  /**
   * Returns a new object of class '<em>Enumeration Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration Literal</em>'.
   * @generated
   */
  EnumerationLiteral createEnumerationLiteral();

  /**
   * Returns a new object of class '<em>Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composition</em>'.
   * @generated
   */
  Composition createComposition();

  /**
   * Returns a new object of class '<em>Element List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element List</em>'.
   * @generated
   */
  ElementList createElementList();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Import Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Clause</em>'.
   * @generated
   */
  ImportClause createImportClause();

  /**
   * Returns a new object of class '<em>Import List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import List</em>'.
   * @generated
   */
  ImportList createImportList();

  /**
   * Returns a new object of class '<em>Extend Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extend Clause</em>'.
   * @generated
   */
  ExtendClause createExtendClause();

  /**
   * Returns a new object of class '<em>Constraining Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraining Clause</em>'.
   * @generated
   */
  ConstrainingClause createConstrainingClause();

  /**
   * Returns a new object of class '<em>Modification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modification</em>'.
   * @generated
   */
  Modification createModification();

  /**
   * Returns a new object of class '<em>Class Modification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Modification</em>'.
   * @generated
   */
  ClassModification createClassModification();

  /**
   * Returns a new object of class '<em>Argument List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument List</em>'.
   * @generated
   */
  ArgumentList createArgumentList();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Element Modification Or Replaceable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Modification Or Replaceable</em>'.
   * @generated
   */
  ElementModificationOrReplaceable createElementModificationOrReplaceable();

  /**
   * Returns a new object of class '<em>Element Modification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Modification</em>'.
   * @generated
   */
  ElementModification createElementModification();

  /**
   * Returns a new object of class '<em>Element Redeclaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Redeclaration</em>'.
   * @generated
   */
  ElementRedeclaration createElementRedeclaration();

  /**
   * Returns a new object of class '<em>Element Replaceable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Replaceable</em>'.
   * @generated
   */
  ElementReplaceable createElementReplaceable();

  /**
   * Returns a new object of class '<em>Component Clause1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Clause1</em>'.
   * @generated
   */
  ComponentClause1 createComponentClause1();

  /**
   * Returns a new object of class '<em>Component Declaration1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Declaration1</em>'.
   * @generated
   */
  ComponentDeclaration1 createComponentDeclaration1();

  /**
   * Returns a new object of class '<em>Short Class Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Short Class Definition</em>'.
   * @generated
   */
  ShortClassDefinition createShortClassDefinition();

  /**
   * Returns a new object of class '<em>Component Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Clause</em>'.
   * @generated
   */
  ComponentClause createComponentClause();

  /**
   * Returns a new object of class '<em>Type Prefix</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Prefix</em>'.
   * @generated
   */
  TypePrefix createTypePrefix();

  /**
   * Returns a new object of class '<em>Type Specifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Specifier</em>'.
   * @generated
   */
  TypeSpecifier createTypeSpecifier();

  /**
   * Returns a new object of class '<em>Component List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component List</em>'.
   * @generated
   */
  ComponentList createComponentList();

  /**
   * Returns a new object of class '<em>Component Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Declaration</em>'.
   * @generated
   */
  ComponentDeclaration createComponentDeclaration();

  /**
   * Returns a new object of class '<em>Condition Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Attribute</em>'.
   * @generated
   */
  ConditionAttribute createConditionAttribute();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>Equation Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equation Section</em>'.
   * @generated
   */
  EquationSection createEquationSection();

  /**
   * Returns a new object of class '<em>Algorithm Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithm Section</em>'.
   * @generated
   */
  AlgorithmSection createAlgorithmSection();

  /**
   * Returns a new object of class '<em>Equation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equation</em>'.
   * @generated
   */
  Equation createEquation();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Equation If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equation If</em>'.
   * @generated
   */
  EquationIf createEquationIf();

  /**
   * Returns a new object of class '<em>Statement If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement If</em>'.
   * @generated
   */
  StatementIf createStatementIf();

  /**
   * Returns a new object of class '<em>Equation For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equation For</em>'.
   * @generated
   */
  EquationFor createEquationFor();

  /**
   * Returns a new object of class '<em>Statement For</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement For</em>'.
   * @generated
   */
  StatementFor createStatementFor();

  /**
   * Returns a new object of class '<em>For Indices</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>For Indices</em>'.
   * @generated
   */
  ForIndices createForIndices();

  /**
   * Returns a new object of class '<em>For Index</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>For Index</em>'.
   * @generated
   */
  ForIndex createForIndex();

  /**
   * Returns a new object of class '<em>Statement While</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement While</em>'.
   * @generated
   */
  StatementWhile createStatementWhile();

  /**
   * Returns a new object of class '<em>Equation When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equation When</em>'.
   * @generated
   */
  EquationWhen createEquationWhen();

  /**
   * Returns a new object of class '<em>Statement When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement When</em>'.
   * @generated
   */
  StatementWhen createStatementWhen();

  /**
   * Returns a new object of class '<em>Connect Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Connect Clause</em>'.
   * @generated
   */
  ConnectClause createConnectClause();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name</em>'.
   * @generated
   */
  Name createName();

  /**
   * Returns a new object of class '<em>Component Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Reference</em>'.
   * @generated
   */
  ComponentReference createComponentReference();

  /**
   * Returns a new object of class '<em>Function Call Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Call Args</em>'.
   * @generated
   */
  FunctionCallArgs createFunctionCallArgs();

  /**
   * Returns a new object of class '<em>Function Arguments</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Arguments</em>'.
   * @generated
   */
  FunctionArguments createFunctionArguments();

  /**
   * Returns a new object of class '<em>Named Arguments</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Named Arguments</em>'.
   * @generated
   */
  NamedArguments createNamedArguments();

  /**
   * Returns a new object of class '<em>Named Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Named Argument</em>'.
   * @generated
   */
  NamedArgument createNamedArgument();

  /**
   * Returns a new object of class '<em>Function Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Argument</em>'.
   * @generated
   */
  FunctionArgument createFunctionArgument();

  /**
   * Returns a new object of class '<em>Output Expression List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Expression List</em>'.
   * @generated
   */
  OutputExpressionList createOutputExpressionList();

  /**
   * Returns a new object of class '<em>Expr Expression List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Expression List</em>'.
   * @generated
   */
  ExprExpressionList createExprExpressionList();

  /**
   * Returns a new object of class '<em>Array Subscripts</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Array Subscripts</em>'.
   * @generated
   */
  ArraySubscripts createArraySubscripts();

  /**
   * Returns a new object of class '<em>Subscript</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subscript</em>'.
   * @generated
   */
  Subscript createSubscript();

  /**
   * Returns a new object of class '<em>Comment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comment</em>'.
   * @generated
   */
  Comment createComment();

  /**
   * Returns a new object of class '<em>String Comment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Comment</em>'.
   * @generated
   */
  StringComment createStringComment();

  /**
   * Returns a new object of class '<em>Assert</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assert</em>'.
   * @generated
   */
  Assert createAssert();

  /**
   * Returns a new object of class '<em>Annotation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation</em>'.
   * @generated
   */
  Annotation createAnnotation();

  /**
   * Returns a new object of class '<em>Annotation Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Arg</em>'.
   * @generated
   */
  AnnotationArg createAnnotationArg();

  /**
   * Returns a new object of class '<em>Def Component Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Def Component Name</em>'.
   * @generated
   */
  DefComponentName createDefComponentName();

  /**
   * Returns a new object of class '<em>Choices</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Choices</em>'.
   * @generated
   */
  Choices createChoices();

  /**
   * Returns a new object of class '<em>Annotation Code</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Code</em>'.
   * @generated
   */
  AnnotationCode createAnnotationCode();

  /**
   * Returns a new object of class '<em>Annotation Layer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Layer</em>'.
   * @generated
   */
  AnnotationLayer createAnnotationLayer();

  /**
   * Returns a new object of class '<em>Layer Icon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Layer Icon</em>'.
   * @generated
   */
  LayerIcon createLayerIcon();

  /**
   * Returns a new object of class '<em>Layer Diagram</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Layer Diagram</em>'.
   * @generated
   */
  LayerDiagram createLayerDiagram();

  /**
   * Returns a new object of class '<em>Coordinate Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Coordinate Specification</em>'.
   * @generated
   */
  CoordinateSpecification createCoordinateSpecification();

  /**
   * Returns a new object of class '<em>Coordinate Specification Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Coordinate Specification Args</em>'.
   * @generated
   */
  CoordinateSpecificationArgs createCoordinateSpecificationArgs();

  /**
   * Returns a new object of class '<em>Extent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extent</em>'.
   * @generated
   */
  Extent createExtent();

  /**
   * Returns a new object of class '<em>Preserve AR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Preserve AR</em>'.
   * @generated
   */
  PreserveAR createPreserveAR();

  /**
   * Returns a new object of class '<em>Initial Scale</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Scale</em>'.
   * @generated
   */
  InitialScale createInitialScale();

  /**
   * Returns a new object of class '<em>Grid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Grid</em>'.
   * @generated
   */
  Grid createGrid();

  /**
   * Returns a new object of class '<em>Placement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Placement</em>'.
   * @generated
   */
  Placement createPlacement();

  /**
   * Returns a new object of class '<em>Placement Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Placement Arg</em>'.
   * @generated
   */
  PlacementArg createPlacementArg();

  /**
   * Returns a new object of class '<em>Visible</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Visible</em>'.
   * @generated
   */
  Visible createVisible();

  /**
   * Returns a new object of class '<em>Transformation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformation</em>'.
   * @generated
   */
  Transformation createTransformation();

  /**
   * Returns a new object of class '<em>Transformation Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformation Arg</em>'.
   * @generated
   */
  TransformationArg createTransformationArg();

  /**
   * Returns a new object of class '<em>Rotation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotation</em>'.
   * @generated
   */
  Rotation createRotation();

  /**
   * Returns a new object of class '<em>Origin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Origin</em>'.
   * @generated
   */
  Origin createOrigin();

  /**
   * Returns a new object of class '<em>Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Point</em>'.
   * @generated
   */
  Point createPoint();

  /**
   * Returns a new object of class '<em>Radius</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Radius</em>'.
   * @generated
   */
  Radius createRadius();

  /**
   * Returns a new object of class '<em>Smooth</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Smooth</em>'.
   * @generated
   */
  Smooth createSmooth();

  /**
   * Returns a new object of class '<em>Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color</em>'.
   * @generated
   */
  Color createColor();

  /**
   * Returns a new object of class '<em>Thickness</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Thickness</em>'.
   * @generated
   */
  Thickness createThickness();

  /**
   * Returns a new object of class '<em>Graphics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphics</em>'.
   * @generated
   */
  Graphics createGraphics();

  /**
   * Returns a new object of class '<em>Graphical Primitive</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphical Primitive</em>'.
   * @generated
   */
  GraphicalPrimitive createGraphicalPrimitive();

  /**
   * Returns a new object of class '<em>Line</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line</em>'.
   * @generated
   */
  Line createLine();

  /**
   * Returns a new object of class '<em>Polygon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Polygon</em>'.
   * @generated
   */
  Polygon createPolygon();

  /**
   * Returns a new object of class '<em>Rectangle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rectangle</em>'.
   * @generated
   */
  Rectangle createRectangle();

  /**
   * Returns a new object of class '<em>Ellipse</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ellipse</em>'.
   * @generated
   */
  Ellipse createEllipse();

  /**
   * Returns a new object of class '<em>Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text</em>'.
   * @generated
   */
  Text createText();

  /**
   * Returns a new object of class '<em>Bitmap</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bitmap</em>'.
   * @generated
   */
  Bitmap createBitmap();

  /**
   * Returns a new object of class '<em>Graphical Primitive Args</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphical Primitive Args</em>'.
   * @generated
   */
  GraphicalPrimitiveArgs createGraphicalPrimitiveArgs();

  /**
   * Returns a new object of class '<em>Dialog</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dialog</em>'.
   * @generated
   */
  Dialog createDialog();

  /**
   * Returns a new object of class '<em>Dialog Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dialog Arg</em>'.
   * @generated
   */
  DialogArg createDialogArg();

  /**
   * Returns a new object of class '<em>Enable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enable</em>'.
   * @generated
   */
  Enable createEnable();

  /**
   * Returns a new object of class '<em>Group</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group</em>'.
   * @generated
   */
  Group createGroup();

  /**
   * Returns a new object of class '<em>Tab</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tab</em>'.
   * @generated
   */
  Tab createTab();

  /**
   * Returns a new object of class '<em>Annotation Documentation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Documentation</em>'.
   * @generated
   */
  AnnotationDocumentation createAnnotationDocumentation();

  /**
   * Returns a new object of class '<em>Annotation Experiment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Experiment</em>'.
   * @generated
   */
  AnnotationExperiment createAnnotationExperiment();

  /**
   * Returns a new object of class '<em>Experiment Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Experiment Option</em>'.
   * @generated
   */
  ExperimentOption createExperimentOption();

  /**
   * Returns a new object of class '<em>Logical Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Expression</em>'.
   * @generated
   */
  LogicalExpression createLogicalExpression();

  /**
   * Returns a new object of class '<em>Logical Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Term</em>'.
   * @generated
   */
  LogicalTerm createLogicalTerm();

  /**
   * Returns a new object of class '<em>Relation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation</em>'.
   * @generated
   */
  Relation createRelation();

  /**
   * Returns a new object of class '<em>Arithmetic Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Expression</em>'.
   * @generated
   */
  ArithmeticExpression createArithmeticExpression();

  /**
   * Returns a new object of class '<em>Arithmetic Expression2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Expression2</em>'.
   * @generated
   */
  ArithmeticExpression2 createArithmeticExpression2();

  /**
   * Returns a new object of class '<em>Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term</em>'.
   * @generated
   */
  Term createTerm();

  /**
   * Returns a new object of class '<em>Factor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Factor</em>'.
   * @generated
   */
  Factor createFactor();

  /**
   * Returns a new object of class '<em>Primary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primary</em>'.
   * @generated
   */
  Primary createPrimary();

  /**
   * Returns a new object of class '<em>Output Expresion List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Expresion List</em>'.
   * @generated
   */
  OutputExpresionList createOutputExpresionList();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ModelicaMoPackage getModelicaMoPackage();

} //ModelicaMoFactory
