/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Modification#getClassModification <em>Class Modification</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Modification#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getModification()
 * @model
 * @generated
 */
public interface Modification extends EObject
{
  /**
   * Returns the value of the '<em><b>Class Modification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Class Modification</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Modification</em>' containment reference.
   * @see #setClassModification(ClassModification)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getModification_ClassModification()
   * @model containment="true"
   * @generated
   */
  ClassModification getClassModification();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Modification#getClassModification <em>Class Modification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Modification</em>' containment reference.
   * @see #getClassModification()
   * @generated
   */
  void setClassModification(ClassModification value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getModification_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Modification#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

} // Modification
