/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package sc.modelica.xtext.modelicaMo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Statement#getComponent <em>Component</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Statement#getExpression <em>Expression</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Statement#getFca <em>Fca</em>}</li>
 *   <li>{@link sc.modelica.xtext.modelicaMo.Statement#getComm <em>Comm</em>}</li>
 * </ul>
 *
 * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Component</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' containment reference.
   * @see #setComponent(ComponentReference)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getStatement_Component()
   * @model containment="true"
   * @generated
   */
  ComponentReference getComponent();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Statement#getComponent <em>Component</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' containment reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(ComponentReference value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getStatement_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Statement#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Fca</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fca</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fca</em>' containment reference.
   * @see #setFca(FunctionCallArgs)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getStatement_Fca()
   * @model containment="true"
   * @generated
   */
  FunctionCallArgs getFca();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Statement#getFca <em>Fca</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fca</em>' containment reference.
   * @see #getFca()
   * @generated
   */
  void setFca(FunctionCallArgs value);

  /**
   * Returns the value of the '<em><b>Comm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comm</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comm</em>' containment reference.
   * @see #setComm(Comment)
   * @see sc.modelica.xtext.modelicaMo.ModelicaMoPackage#getStatement_Comm()
   * @model containment="true"
   * @generated
   */
  Comment getComm();

  /**
   * Sets the value of the '{@link sc.modelica.xtext.modelicaMo.Statement#getComm <em>Comm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comm</em>' containment reference.
   * @see #getComm()
   * @generated
   */
  void setComm(Comment value);

} // Statement
